### ISSUE TITLE
Sticky notes: Movable textboxes (with colored backgrounds)

### ISSUE THREAD

**Issue by DrSky2007** [lovasoa/whitebophir#165] opened 2021-01-29 15:36 UTC
I'm not a programmer, but I love WBO! The only thing I am realy missing is the possibility to create **textboxes with specific sizes**, which are movable (like **sticky notes**). Maybe it is also possible to give them individual colored backgrounds.

Thank you for your work! Would like to support it with a donation.

**Comment by lovasoa** [comment] 2021-01-29 16:56
Hello, and thank you for getting in touch. It's nice to see people like WBO.

I am going to close this issue as a duplicate of #76, but we keep it open and can discuss it there. 

If you want to donate, you can use [github sponsors](https://github.com/sponsors/lovasoa) or my [personal paypal](https://paypal.me/olojkine).

**Closed by lovasoa** 2021-01-29 16:56 UTC
