### ISSUE TITLE
support for PointerEvent.pressure

### ISSUE THREAD

**Issue by toger5** [lovasoa/whitebophir#204] opened 2021-06-08 13:55 UTC
It would be great to have support for **PointerEvent.pressure**:
https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pressure
This can highly improve the look and feel of the writing area when using a wacome (or sth similar) tablet.

I really enjoy using the board but it just lacks behind in the actual drawing look when compared to sth like xournal++ or oneNote.

**Comment by toger5** [comment] 2021-06-08 14:02
This request is based on #3
(Could even be considered a duplicate. Feel free to close if it is considered a duplicate)

**Comment by lovasoa** [comment] 2021-06-08 14:41
I'm closing this as a duplicate of #3, but this is a good feature. Pull requests welcome :)
This is actually probably a lot of work to implement, because shapes are currently always stored as a list of points and a width, and this would require switching to something more complex.

**Closed by lovasoa** 2021-06-08 14:41 UTC
