### ISSUE TITLE
Clear All button in the Menu

### ISSUE THREAD

**Issue by SushantGautam** [lovasoa/whitebophir#212] opened 2021-06-15 08:35 UTC
I think it's worth having **a clear all button** in the Menu.
We can fire an alert for confirmation to prevent accidents.
This can be disabled by default but if there is such an option in config. to enable the button it can be very handy for teachers who resue the board.

**Comment by lovasoa** [comment] 2021-06-15 08:43
Duplicate of https://github.com/lovasoa/whitebophir/issues/92

See
 - #152
 -  #202

**Closed by lovasoa** 2021-06-15 08:43 UTC
