### ISSUE TITLE
superimposing an image , alpha setting variable

### ISSUE THREAD

**Issue by beccobunsen** [lovasoa/whitebophir#93] opened 2020-06-19 18:20 UTC
the blackboard is spectacular. It would be wonderful to have the possibility of superimposing an image for fine motor skills for children who start writing!

**Comment by lovasoa** [comment] 2020-06-20 14:50
Duplicate of #20

**Comment by lovasoa** [comment] 2020-06-20 14:51
Hello, and thank you for contributing. Let's merge this issue with #20.

**Closed by lovasoa** 2020-06-20 14:50 UTC
Labels: duplicate, enhancement
