### ISSUE TITLE
Preview as SVG doesn't correspond to the real whiteboard content

### ISSUE THREAD

**Issue by piiskop** [lovasoa/whitebophir#162] opened 2021-01-15 09:42 UTC
I have a public [whiteboard](http://whitebophir.tennis24.ee/boards/matemaatika#0,838,1.0). If I replace _boards_ in its address by _preview_ then I see an SVG-version of it that misses the content below I created a day ago by showing only some old drawings.

I've also noticed that these old drawings always remain and after a while, newer drawings disappear.

**Comment by lovasoa** [comment] 2021-01-15 11:39
I'm getting a `502 Bad Gateway` when trying to access your link.

The board preview uses the on-disk whiteboard, which may lack a few seconds of the most recent data. You can configure the disk persistence interval using the `WBO_SAVE_INTERVAL` and `WBO_MAX_SAVE_DELAY` environment variables. See the [list of configuration variables and their description](https://github.com/lovasoa/whitebophir/blob/master/server/configuration.js#L19-L23).

If you need more help, please provide a detailed list of steps to reproduce your issue.

**Comment by piiskop** [comment] 2021-01-15 12:35
You wer getting that error message because the app wasn't running currently as I wanted to restart the server machine and there's no automation for _whitebophir_ to restart it automatically. It is running now.

The lack wasn't a few seconds. The lack was a few hours. I haven't changed the defaults.

Now, the anomaly doesn't appear. However when I meet it again I report it.

After the server restart, the particular whiteboard still has very old data that never disappears, only some newer lines and things keep disappearing. [Another public whiteboard](http://whitebophir.tennis24.ee/boards/arvutiteadus) looses everything after a while constantly.

**Comment by lovasoa** [comment] 2021-01-15 13:28
It looks like WBO is having troubles saving files on your server. What do the logs say ? Whiteboard saving errors should appear in the logs, and you should be able to see where the error comes from.

Also, you should use docker to restart wbo automatically when your server reboots (and when it crashes).

**Comment by piiskop** [comment] 2021-01-15 13:51
I avoid _docker_ as much as possible as it's too complicated to handle. This is why I don't run _whitebophir_ inside _docker_.

_nginx_ hasn't reported any errors on _whitebophir_.

There's an error message in the browser's console:
[whitebophir.tennis24.ee-1610718590528.log](https://github.com/lovasoa/whitebophir/files/5820856/whitebophir.tennis24.ee-1610718590528.log)

Maybe, a proper way to restart the app automatically is to use _supervisorctl_.

**Comment by lovasoa** [comment] 2021-01-15 14:17
What you should look at is not the nginx logs, nor the browser console logs, but the logs of the application itself. How to access them depends on how you launched the application on your server. What you need is what the wbo process wrote to its standard output and standard error streams. If you are launching wbo manually using npm, you can collect that to a file by launching the process like that `npm start > output.log 2> error.log`. Then post output.log and error.log here.

And using wbo inside docker should be easier (and safer), not more complicated. A single command and you have logs management, easy updates, automatic restart, and so on:

```
sudo docker run --publish 80:8080 --volume "$PWD/wbo-boards:/opt/app/server-data" --name wbo --detach --restart unless-stopped lovasoa/wbo:latest
```

**Comment by piiskop** [comment] 2021-01-15 15:53
Your given command didn't give anything. And yes, I use _PORT=1024 npm start_ for starting the app.

Isn't _docker_-way slower? Even your startup string is so long that it needs a scrollbar. And if I want to get into that _docker_ I need some additional knowledge. Do I get it correctly that _docker_ also uses more memory as all that stuff outside _docker_ must be repeated inside it?

**Comment by lovasoa** [comment] 2021-01-15 17:05
What do you mean it didn't give anything ? The command just starts wbo, redirecting the standard output to a file. You should then use wbo, reproduce your error, then fetch the files and post them here. 

Docker doesn't have any performance impact, the wbo process will run natively on your system, without any virtualization or emulation. It does use slightly more memory and disk space, but this should be insignificant in comparison to what wbo itself will use.

**Comment by piiskop** [comment] 2021-01-15 18:18
I didn't know that I had to use your command within the folder of _whitebophir_. I used your command within that folder and got still nothing. Then, I realized that I have to look for the file _error.log_ which contains no useful information:

> events.js:298
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE: address already in use :::8080
>     at Server.setupListenHandle [as _listen2] (net.js:1309:16)
>     at listenInCluster (net.js:1357:12)
>     at Server.listen (net.js:1445:7)
>     at Object.<anonymous> (/projektid/whitebophir/server/server.js:25:5)
>     at Module._compile (internal/modules/cjs/loader.js:1157:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
>     at Module.load (internal/modules/cjs/loader.js:1001:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:900:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
>     at internal/main/run_main_module.js:18:47
> Emitted 'error' event on Server instance at:
>     at emitErrorNT (net.js:1336:8)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   code: 'EADDRINUSE',
>   errno: 'EADDRINUSE',
>   syscall: 'listen',
>   address: '::',
>   port: 8080
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! whitebophir@1.6.5 start: `node ./server/server.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the whitebophir@1.6.5 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:

**Comment by lovasoa** [comment] 2021-01-15 18:32
of course you have to stop your running instance, and set the PORT variable appropriately

**Comment by piiskop** [comment] 2021-01-15 19:28
> kalmer@test:/projektid/whitebophir$ PORT=1024 npm start
> 
> > whitebophir@1.6.5 start /projektid/whitebophir
> > node ./server/server.js
> 
> 2021-01-15T12:20:19.177Z	server started	{"port":1024}
> 2021-01-15T12:20:35.079Z	connection	{"ip":"::ffff:127.0.0.1","original_ip":"192.168.1.1","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","language":"et-EE,et;q=0.9,en-US;q=0.8,en;q=0.7","url":"/"}
> 2021-01-15T12:26:38.338Z	disk load	{"board":"matemaatika"}
> 2021-01-15T12:26:38.338Z	board joined	{"board":"matemaatika","users":1}
> 2021-01-15T12:31:05.610Z	saved board	{"name":"matemaatika","size":166509,"delay_ms":13}
> 2021-01-15T12:31:08.151Z	saved board	{"name":"matemaatika","size":166528,"delay_ms":7}
> 2021-01-15T12:31:10.953Z	preview	{"board":"matemaatika","time":27}
> 2021-01-15T12:31:11.140Z	disconnection	{"board":"matemaatika","users":0}
> 2021-01-15T12:31:11.147Z	saved board	{"name":"matemaatika","size":166528,"delay_ms":7}
> 2021-01-15T12:34:04.228Z	disk load	{"board":"matemaatika"}
> 2021-01-15T12:34:04.228Z	board joined	{"board":"matemaatika","users":1}
> 2021-01-15T12:34:14.779Z	disconnection	{"board":"matemaatika","users":0}
> 2021-01-15T12:34:14.786Z	saved board	{"name":"matemaatika","size":166528,"delay_ms":7}
> 2021-01-15T12:34:20.011Z	disk load	{"board":"matemaatika"}
> 2021-01-15T12:34:20.011Z	board joined	{"board":"matemaatika","users":1}
> 2021-01-15T12:34:31.189Z	disconnection	{"board":"matemaatika","users":0}
> 2021-01-15T12:34:31.196Z	saved board	{"name":"matemaatika","size":166528,"delay_ms":7}
> 2021-01-15T12:34:42.568Z	empty board creation	{"board":"arvutiteadus","error":false}
> 2021-01-15T12:34:42.568Z	board joined	{"board":"arvutiteadus","users":1}
> 2021-01-15T12:35:36.656Z	empty board creation	{"board":"arvutiteadus)","error":false}
> 2021-01-15T12:35:36.656Z	board joined	{"board":"arvutiteadus)","users":1}
> 2021-01-15T12:35:39.288Z	board joined	{"board":"arvutiteadus","users":2}
> 2021-01-15T12:35:46.495Z	board joined	{"board":"arvutiteadus)","users":2}
> 2021-01-15T12:35:53.144Z	board joined	{"board":"arvutiteadus)","users":3}
> 2021-01-15T12:36:11.673Z	disconnection	{"board":"arvutiteadus","users":1}
> 2021-01-15T12:37:50.145Z	disconnection	{"board":"arvutiteadus","users":0}
> 2021-01-15T12:37:55.076Z	disconnection	{"board":"arvutiteadus)","users":2}
> 2021-01-15T12:38:03.214Z	disconnection	{"board":"arvutiteadus)","users":1}
> 2021-01-15T12:38:11.642Z	disconnection	{"board":"arvutiteadus)","users":0}
> 2021-01-15T13:24:14.967Z	error	{"url":"/robots.txt"}
> 2021-01-15T13:25:21.351Z	empty board creation	{"board":"arvutiteadus","error":false}
> 2021-01-15T13:25:21.351Z	board joined	{"board":"arvutiteadus","users":1}
> 2021-01-15T13:25:26.967Z	disconnection	{"board":"arvutiteadus","users":0}
> 2021-01-15T13:25:33.969Z	disk load	{"board":"matemaatika"}
> 2021-01-15T13:25:33.969Z	board joined	{"board":"matemaatika","users":1}
> 2021-01-15T13:25:38.858Z	disconnection	{"board":"matemaatika","users":0}
> 2021-01-15T13:25:38.865Z	saved board	{"name":"matemaatika","size":166528,"delay_ms":7}
> 2021-01-15T13:29:13.389Z	preview	{"board":"matemaatika","time":17}
> 2021-01-15T13:36:02.778Z	connection	{"ip":"::ffff:127.0.0.1","original_ip":"192.168.1.1","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","language":"et-EE,et;q=0.9,en-US;q=0.8,en;q=0.7","url":"/"}
> 2021-01-15T13:36:08.015Z	disk load	{"board":"matemaatika"}
> 2021-01-15T13:36:08.015Z	board joined	{"board":"matemaatika","users":1}
> 2021-01-15T13:52:19.424Z	disconnection	{"board":"matemaatika","users":0}
> 2021-01-15T13:52:19.430Z	saved board	{"name":"matemaatika","size":166528,"delay_ms":6}
> 2021-01-15T16:34:01.291Z	disk load	{"board":"matemaatika"}
> 2021-01-15T16:34:03.314Z	saved board	{"name":"matemaatika","size":166665,"delay_ms":21}
> 2021-01-15T17:38:49.424Z	saved board	{"name":"matemaatika","size":166792,"delay_ms":6}
> 2021-01-15T17:38:54.567Z	saved board	{"name":"matemaatika","size":166806,"delay_ms":9}
> 2021-01-15T17:38:58.246Z	saved board	{"name":"matemaatika","size":166943,"delay_ms":7}
> 2021-01-15T18:49:20.920Z	error	{"url":"/robots.txt"}
> 2021-01-15T18:50:32.196Z	empty board creation	{"board":"arvutiteadus","error":false}
> 2021-01-15T18:50:32.196Z	board joined	{"board":"arvutiteadus","users":1}
> 2021-01-15T18:50:44.807Z	disconnection	{"board":"arvutiteadus","users":0}
> 2021-01-15T18:58:07.838Z	empty board creation	{"board":"arvutiteadus","error":false}
> 2021-01-15T18:58:07.838Z	board joined	{"board":"arvutiteadus","users":1}
> 2021-01-15T18:58:20.505Z	disconnection	{"board":"arvutiteadus","users":0}
> 2021-01-15T19:22:53.216Z	empty board creation	{"board":"arvutiteadus","error":false}
> 2021-01-15T19:22:53.216Z	board joined	{"board":"arvutiteadus","users":1}
> 2021-01-15T19:23:17.827Z	disconnection	{"board":"arvutiteadus","users":0}
>

**Comment by lovasoa** [comment] 2021-01-15 19:50
so, did you reproduce the issue while these logs were running? Because I don't see all boards being saved regularly without errors, and no board preview being triggered...

**Comment by piiskop** [comment] 2021-01-15 19:58
This anomaly won't appear if I want it to. It always appears when it wants and surprises me. Now I know where to see the log as it doesn't run in the background. And once it reappears, I note it here.

**Comment by lovasoa** [comment] 2021-01-15 22:14
Something you could already check now is whether you have enough free space on your disk and whether your drive is healthy.

**Comment by piiskop** [comment] 2021-01-16 07:13
> /dev/sda1       222G  145G   66G  69% /

Enough?

I have _RAID 1_, so there should be no concern on the drive health.

**Comment by piiskop** [comment] 2021-01-16 07:49
![Screenshot at 2021-01-16 09-46-18](https://user-images.githubusercontent.com/14224528/104806390-ccc94c80-57df-11eb-890e-6c538d5790ff.png)
The same whiteboard is having different things on it in different browsers. As you see from the image, on the left are more elements than on the right. The lightblue part in lower right corner was created after the stuff in the lower left corner. And the things in the upper part remain there like forever whereas other things keep disappearing.

**Comment by lovasoa** [comment] 2021-01-17 21:21
You have a badly configured nginx reverse proxy that is refusing websocket connections.

See our wiki: https://github.com/lovasoa/whitebophir/wiki/Setup-behind-Reverse-Proxies

**Comment by piiskop** [comment] 2021-01-18 08:13
I don't use aliases but subdomains. What should I add or change? My configuration:

> server {
>         server_name whitebophir.tennis24.ee;
>         location / {
>                 proxy_set_header  X-Real-IP $remote_addr;
>                 proxy_set_header  X-Forwarded-For $remote_addr;
>                 proxy_set_header  X-Forwarded-Proto $scheme;
>                 proxy_set_header  X-Forwarded-Host $http_host;
>                 proxy_set_header  Host $host;
>                 proxy_http_version  1.1;
>                 proxy_set_header    Upgrade $http_upgrade;
>         #       proxy_set_header    Connection $connection_upgrade;
>                 proxy_pass http://localhost:1024;
>         }
> 
> }

**Comment by lovasoa** [comment] 2021-01-18 15:33
It looks like you commented out the "Connection" header line. See https://www.nginx.com/blog/websocket-nginx/
You should allow websocket connections to /socket.io

Since this doesn't seem to be a bug in WBO, I am closing this. But feel free to keep commenting below, and to update the Wiki if needed.

**Comment by piiskop** [comment] 2021-01-19 09:39
I had commented it out because that line was initially copied from somewhere and broke _nginx_ as it referenced to something obsolete. From your referenced story, I got a correct value to replace that reference. It also worked without it. But some things don't?

**Comment by lovasoa** [comment] 2021-01-19 10:27
Reloading your page, websocket connections are not blocked anymore. 

![image](https://user-images.githubusercontent.com/552629/105021699-21233500-5a49-11eb-8244-4c779d8ad095.png)

This means you don't need to make thousand of network requests to draw a simple shape anymore.

**Comment by piiskop** [comment] 2021-01-19 12:48
So this is why my router shows so many active connections:


> Hostname | MAC Address | IPv4 Address | IPv6 Address | Active Connections
> -- | -- | -- | -- | --
> * | da:a8:f1:19:e0:7b | 192.168.1.171 | N/A | 1
> RedmiNote9Pro-RedmiN | 20:f4:78:78:93:7c | 192.168.1.221 | N/A | 6
> kalmer-GL752VW | 70:8b:cd:01:83:c9 | 192.168.1.245 | N/A | 23
> peacecop-HP-ProBook-4520s | 78:e7:d1:db:c3:bf | 192.168.1.151 | N/A | 4543

**Comment by piiskop** [comment] 2021-02-01 18:04
At least three times in the row, two of my whiteboards - _matemaatika_ and _arvutiteaduse_ have been used heavily so that users have seen everything live but once I replaced _boards_ by _preview_, all the changes have gone lost and an old version have been restored. Nothing gets logged. I show you my system service file content:

> [Unit]
> Description=whiteboard application
> 
> [Service]
> User=www-data
> WorkingDirectory=/projektid/whitebophir
> ExecStart=/usr/local/bin/node /projektid/whitebophir/server/server.js > /projektid/whitebophir/output.log 2> /projektid/whitebophir/error.log
> Environment=PORT=1024
> [Install]
> WantedBy=multi-user.target

What do I do wrong if the software claims to be right?

**Comment by piiskop** [comment] 2021-02-06 09:30
Why is this issue closed if the issue still exists regardless of the configuration change?

**Comment by lovasoa** [comment] 2021-02-06 18:07
Hello,
  Can you provide reproduction instructions ? I cannot reproduce this issue.

**Comment by piiskop** [comment] 2021-02-06 18:37
You can reproduce it on [my board](http://whitebophir.tennis24.ee/boards/matemaatika). Between 14 and 16 EET, I added lots of trigonometric simplifications which are all gone. It happens all the time. You just draw something, refresh the page and see that your drawing is gone!

**Comment by lovasoa** [comment] 2021-02-06 18:50
By reproduction instruction, I mean a list of steps that can be run on any computer to reproduce the issue. If no one can reproduce your issue, then no one can fix it for you, and you will have to fix it yourself.

**Comment by piiskop** [comment] 2021-02-06 18:54
Just use any computer, go to [matemaatika](http://whitebophir.tennis24.ee/boards/matemaatika), draw something on that board, refresh the page, see that your drawing is gone!

**Comment by lovasoa** [comment] 2021-02-06 19:02
Haha ! I need to be able to launch a wbo **server** with the bug to debug it. Or at least get logs that point to the error. Otherwise, this issue is not actionable.

**Comment by piiskop** [comment] 2021-02-06 19:05
I asked a question about how to get the logs five days ago:

> > ExecStart=/usr/local/bin/node /projektid/whitebophir/server/server.js > /projektid/whitebophir/output.log 2> /projektid/whitebophir/error.log
> What do I do wrong if the software claims to be right?

I never got an answer. I'd be glad to serve you with logs if they existed somewhere.

**Comment by lovasoa** [comment] 2021-02-06 19:53
You never mentioned how you were launching wbo, but by this line, I'm guessing you are using systemd : 

> ExecStart=/usr/local/bin/node /projektid/whitebophir/server/server.js > /projektid/whitebophir/output.log 2> /projektid/whitebophir/error.log

I don't think you can use `>` and `2>` inside *ExecStart*. systemd doesnt launch your service through a shell that could interpret those.

You can use journalctl to view the logs of a systemd service :

https://unix.stackexchange.com/questions/20399/view-stdout-stderr-of-systemd-service

**Comment by piiskop** [comment] 2021-02-06 20:48
Thank you for this reference! _journalctl_ shows the following data:

> dets  18 20:20:02 test.tennis24.ee node[18464]: 2020-12-18T18:20:02.848Z        connection        {"ip":"::ffff:192.168.1.65","original_ip":">
> dets  18 20:20:07 test.tennis24.ee node[18464]: 2020-12-18T18:20:07.788Z        disk load        {"board":"matemaatika"}
> dets  18 20:20:07 test.tennis24.ee node[18464]: 2020-12-18T18:20:07.788Z        board joined        {"board":"matemaatika","users":1}
> dets  18 20:20:37 test.tennis24.ee node[18464]: 2020-12-18T18:20:37.865Z        board saving error        {"err":"Error: EACCES: permission d>

The last row is repeated many times. As _journalctl_ doesn't show the full line I use another way to get the full line:

> kalmer@test:~$ cat /var/log/syslog|grep "board"
> Feb  6 08:01:02 test node[1501458]: 2021-02-06T06:01:02.733Z#011error#011{"error":"Error: ENOENT: no such file or directory, open '/projektid/whitebophir/server-data/board-uhf-ZzDhjKcgpYI-gGmn--m8QyBdimqLQsxYnvGM8X0-.json'"}
> Feb  6 11:27:06 test node[1501458]: 2021-02-06T09:27:06.756Z#011disk load#011{"board":"matemaatika"}
> Feb  6 11:27:06 test node[1501458]: 2021-02-06T09:27:06.756Z#011board joined#011{"board":"matemaatika","users":1}
> Feb  6 11:27:21 test node[1501458]: 2021-02-06T09:27:21.886Z#011disk load#011{"board":"arvutiteadus"}
> Feb  6 11:27:21 test node[1501458]: 2021-02-06T09:27:21.886Z#011board joined#011{"board":"arvutiteadus","users":1}
> Feb  6 11:27:47 test node[1501458]: 2021-02-06T09:27:47.346Z#011disconnection#011{"board":"matemaatika","users":0}
> Feb  6 11:27:47 test node[1501458]: 2021-02-06T09:27:47.384Z#011board saving error#011{"err":"Error: EACCES: permission denied, open '/projektid/whitebophir/server-data/board-matemaatika.json.2021-02-06T092747.346Z.bak'","tmp_file":"/projektid/whitebophir/server-data/board-matemaatika.json.2021-02-06T092747.346Z.bak"}

It turns out that I have to manually edit the access rights for the folder _server-data_:

> kalmer@test:/projektid/whitebophir$ l -la
> kokku 324
> drwxr-xr-x  10 kalmer   kalmer     4096 jaan  20 20:59 ./
> drwxrwxrwx  46 www-data www-data   4096 jaan  20 23:06 ../
> -rw-r--r--   1 kalmer   kalmer       38 nov   20 18:45 AUTHORS
> drwxr-xr-x   4 kalmer   kalmer     4096 nov   20 18:45 client-data/
> -rw-r--r--   1 kalmer   kalmer      299 nov   20 18:45 docker-compose.yml
> -rw-r--r--   1 kalmer   kalmer      184 nov   20 18:45 Dockerfile
> -rw-r--r--   1 kalmer   kalmer        0 jaan  16 11:39 error.log
> drwxr-xr-x   8 kalmer   kalmer     4096 jaan  15 15:46 .git/
> drwxr-xr-x   3 kalmer   kalmer     4096 nov   20 18:45 .github/
> -rw-r--r--   1 kalmer   kalmer      183 nov   20 18:45 .gitignore
> -rw-r--r--   1 kalmer   kalmer    34523 nov   20 18:45 LICENSE
> -rw-r--r--   1 kalmer   kalmer      941 nov   20 18:45 nightwatch.conf.js
> drwxr-xr-x 337 kalmer   kalmer    12288 jaan  20 20:59 node_modules/
> -rw-r--r--   1 kalmer   kalmer    68081 jaan  20 10:48 output.log
> -rw-r--r--   1 kalmer   kalmer      714 jaan  20 20:59 package.json
> -rw-r--r--   1 kalmer   kalmer   138578 jaan  20 20:59 package-lock.json
> -rw-r--r--   1 kalmer   kalmer     4313 nov   20 18:45 README.md
> drwxr-xr-x   2 kalmer   kalmer     4096 nov   20 18:45 server/
> drwxr-xr-x   2 kalmer   www-data   4096 jaan  20 10:48 server-data/
> kalmer@test:/projektid/whitebophir$ sudo chown kalmer:www-data -R server-data/
> kalmer@test:/projektid/whitebophir$ sudo chmod 775 -R server-data/

Does it work now?

> kalmer@test:/projektid/whitebophir$ sudo systemctl restart whitebophir.service 

I perform some actions on a board, refresh the page and the new drawing is still there.

> Feb  6 22:45:09 test node[2471156]: 2021-02-06T20:45:09.223Z#011disk load#011{"board":"matemaatika"}
> Feb  6 22:45:09 test node[2471156]: 2021-02-06T20:45:09.223Z#011board joined#011{"board":"matemaatika","users":1}
> Feb  6 22:45:15 test node[2471156]: 2021-02-06T20:45:15.622Z#011saved board#011{"name":"matemaatika","size":2331362,"delay_ms":110}
> Feb  6 22:45:17 test node[2471156]: 2021-02-06T20:45:17.230Z#011disconnection#011{"board":"matemaatika","users":0}
> Feb  6 22:45:17 test node[2471156]: 2021-02-06T20:45:17.297Z#011saved board#011{"name":"matemaatika","size":2331362,"delay_ms":67}
> Feb  6 22:45:17 test node[2471156]: 2021-02-06T20:45:17.520Z#011disk load#011{"board":"matemaatika"}
> Feb  6 22:45:17 test node[2471156]: 2021-02-06T20:45:17.520Z#011board joined#011{"board":"matemaatika","users":1}

_whitebophir_ stores the data again.

The permission information is missing in _README.md_.

**Comment by lovasoa** [comment] 2021-02-06 20:58
Ok, this is a duplicate of #164.

It looks like you are launching wbo with the user www-data. The folder where you store boards should belong to that user.

You should update to the latest version of WBO, it performs all the required performance checks on startup, and will refuse to start if you are launching it with a random user without taking care of folder permissions.

What do you think you be changed in the README ? To me, it looks like the problem was entirely on your side; you created a systemd service on your own (sidestepping the recommended docker configuration), and misconfigured it by setting an `User` that didn't have the permissions to write in your boards directory.

**Closed by lovasoa** 2021-02-06 20:58 UTC
Labels: needinfo

**Comment by piiskop** [comment] 2021-02-06 21:24
I just upgraded to _1.7.2_.

I sidestepped the recommended _docker_ configuration as I don't understand the recommended _docker_ configuration in detail and starting _docker_ container takes time and the command is quite long without clear description what all the parameters mean and do. Maybe _docker_ configuration is the best but I don't buy the idea before I fully understand it.

It's a nice touch if the new version checks for the permissions. I meant that _README_ didn't contain that information and _Wiki_ didn't neither before that permission check was added.

**Comment by piiskop** [comment] 2021-03-09 18:40
![trapets](https://user-images.githubusercontent.com/14224528/110520783-993bdc00-8117-11eb-8c77-9fdc60eab456.png)
![cap_2021-03-01 17-58-20_02:08:19_01](https://user-images.githubusercontent.com/14224528/110520871-b1abf680-8117-11eb-9b0d-e919e633b305.jpg)
Please compare. See that the color-filled parts are different!

**Comment by lovasoa** [comment] 2021-03-10 09:34
Yes I see. Without looking at it deeper, I would say that you are hitting the server's rate limit. Rate limiting is present to protect the server from attacks where a single user would flood it with updates

You can configure the various server limits with environment variables: https://github.com/lovasoa/whitebophir/blob/master/server/configuration.js

The two most important for you are probably `WBO_MAX_CHILDREN` and `WBO_MAX_EMIT_COUNT`.

**Comment by lovasoa** [comment] 2021-03-10 09:39
The default values are meant to err on the safe side. They are suitable for a public WBO instance with significant traffic running on a shared VM. If you have a private instance with few users, and reasonably powerful hardware, you should be able to significantly increase these limits.

**Comment by piiskop** [comment] 2021-03-10 13:22
> The two most important for you are probably `WBO_MAX_CHILDREN` and `WBO_MAX_EMIT_COUNT`.

How can I change their values? In _configuration.js_, they're just being read in from somewhere else (_process.env['WBO_MAX_EMIT_COUNT']_)

**Comment by lovasoa** [comment] 2021-03-10 16:32
Yes, these are [environment variables](https://en.wikipedia.org/wiki/Environment_variable).

**Comment by lovasoa** [comment] 2021-03-10 18:09
> What's a subitem? What's an item?

I don't understand this question.

> How can it be that only filling with color will be reduced although the fill is only one item and everything else remains as it should be?

You have created a long thick line with many points in order to fill an area. If you moved your mouse very fast to create this line, you may have exceeded `WBO_MAX_EMIT_COUNT`. If you created a very long line without ever releasing your mouse, you may have exceeded `WBO_MAX_CHILDREN`. You should explicitly set these two environment variables to higher values.

For instance, if you are using the official WBO docker container (which  I hope you are), you can launch it like so 

```
docker run -it --publish 5001:8080 --env WBO_MAX_CHILDREN=999 --env WBO_MAX_EMIT_COUNT=999 lovasoa/wbo:latest
```

**Comment by piiskop** [comment] 2021-03-10 18:22
> > What's a subitem? What's an item?
> 
> I don't understand this question.

```
    /** Max number of sub-items in an item. This prevents flooding */
    MAX_CHILDREN: parseInt(process.env['WBO_MAX_CHILDREN']) || 192,
```
From your answer, I see that a sub-item is a turning point of a line.

As there's no option to fill areas by color, I have to do it as I do it on a physical board: by creating a very long line with many turns that represent a line. This takes memory. Hence, this should be a case where the virtual world must differ from real world as this problem can be avoided by using filling options which aren't yet present. Do you think I created a line with more than 192 turns by filling a triangle? I don't think so.

I'm not running _whitebophir_ as a _docker_ container as mentioned previously. Only if you explain how to do it in details so that I understand every single detail I'd agree to use _docker_ way.

**Comment by lovasoa** [comment] 2021-03-11 06:22
Hey, this is free software, you can use it however you want :) It doesn't make any difference to me how you are using it, it's only better for you (from a security point of view) to use docker. 
Anyway, you can set environment variables whether you are running it in docker or not. Please do restart wbo with the right env variables, retry filling your triangle, and let us know if it worked.

**Comment by piiskop** [comment] 2021-03-11 07:34
Filling this way takes time anyway and it's very unprecise. What do you think of the idea using filling options for closed shapes?

Another thought came to my mind that no virtual whiteboard has a compass that can be used to show how to half an angle or segment or draw a circle or a perpendicular line.

**Comment by lovasoa** [comment] 2021-03-11 14:21
> What do you think of the idea using filling options for closed shapes?

In the current state of WBO, I'm against it. It is hard to implement, and easy to abuse by misbehaving users.

To draw straight shapes, half angles, circles, and perpendicular lines, you can keep shift pressed while you are drawing.

Did you change the env variables ?

**Comment by piiskop** [comment] 2021-03-11 15:19
I didn't change the env variables as this would only probably solve the current filling option taken that there are really more than 192 turning points per fill. You're against adding filling closed shapes because you think some people would fill everything. However if you add an option to undo and see who did what these misbehaving users can be handled.

I didn't mean to ask how to draw circles in the current state. I know how to draw them - there's a button state for it. My question was rather to use a real-looking compass to draw them with as pupils need to learn where to put the needle and how to regulate the distance between the legs of the compass. In real life, you couldn't draw a circle by just shifting your hand on a wood piece for instance. Meanwhile, I found two places where we can do that: [robocompass](https://www.robocompass.com/) and [Mathspad](https://www.mathspad.co.uk/i2/construct.php).
